<#
.SYNOPSIS
    Configures eRemote client to connect to your MSP server.

.DESCRIPTION
    This script configures eRemote to:
    - Use your custom ID/Rendezvous server
    - Use your custom Relay server
    - Disable public RustDesk servers
    - Optionally enable unattended access
    
    SECURITY: Server addresses are passed via NinjaOne variables.
    No secrets are hardcoded in this script.

.PARAMETER Server
    The hostname or IP of your eRemote server.
    In NinjaOne, use custom field: eRemoteServer

.PARAMETER UnattendedPassword
    Optional password for unattended access.
    In NinjaOne, use SECURE custom field: eRemoteUnattendedPassword
    
.NOTES
    NinjaOne Setup:
    1. Create custom field "eRemoteServer" (text)
    2. Create custom field "eRemoteID" (text) - script will populate this
    3. Optionally create secure field "eRemoteUnattendedPassword"
    4. Run this script after Install-eRemote.ps1
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $false)]
    [string]$Server = $env:eRemoteServer,
    
    [Parameter(Mandatory = $false)]
    [string]$UnattendedPassword = $env:eRemoteUnattendedPassword,
    
    [Parameter(Mandatory = $false)]
    [string]$RelayServer = $env:eRemoteRelayServer
)

$ErrorActionPreference = "Stop"

function Write-Log {
    param([string]$Message)
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    Write-Host "[$timestamp] $Message"
}

function Get-eRemoteConfigPath {
    $possiblePaths = @(
        "$env:APPDATA\eRemote\config\eRemote.toml",
        "$env:APPDATA\RustDesk\config\RustDesk.toml",
        "$env:ProgramData\eRemote\config\eRemote.toml"
    )
    
    foreach ($path in $possiblePaths) {
        $dir = Split-Path $path -Parent
        if (Test-Path $dir) {
            return $path
        }
    }
    
    # Create default config directory
    $defaultPath = "$env:APPDATA\eRemote\config\eRemote.toml"
    $defaultDir = Split-Path $defaultPath -Parent
    New-Item -ItemType Directory -Path $defaultDir -Force | Out-Null
    return $defaultPath
}

function Get-eRemoteID {
    # Try to read existing ID from config or generate
    $configPath = Get-eRemoteConfigPath
    
    if (Test-Path $configPath) {
        $content = Get-Content $configPath -Raw
        if ($content -match 'id\s*=\s*"?(\d+)"?') {
            return $matches[1]
        }
    }
    
    # Try to get ID from running process or service
    $exePaths = @(
        "$env:ProgramFiles\eRemote\eRemote.exe",
        "$env:ProgramFiles\RustDesk\rustdesk.exe"
    )
    
    foreach ($exePath in $exePaths) {
        if (Test-Path $exePath) {
            try {
                $output = & $exePath --get-id 2>&1
                if ($output -match '^\d+$') {
                    return $output.Trim()
                }
            }
            catch {
                # Continue to next method
            }
        }
    }
    
    return $null
}

try {
    Write-Log "=== eRemote Configuration Starting ==="
    
    # Validate server parameter
    if ([string]::IsNullOrWhiteSpace($Server)) {
        throw "Server address is required. Set the eRemoteServer NinjaOne custom field or pass -Server parameter."
    }
    
    # Use same server for relay if not specified
    if ([string]::IsNullOrWhiteSpace($RelayServer)) {
        $RelayServer = $Server
    }
    
    Write-Log "ID Server: $Server"
    Write-Log "Relay Server: $RelayServer"
    
    # Get config file path
    $configPath = Get-eRemoteConfigPath
    Write-Log "Config path: $configPath"
    
    # Build configuration content
    $configContent = @"
# eRemote Configuration
# Generated by Configure-eRemote.ps1
# DO NOT EDIT MANUALLY - changes may be overwritten

[options]
# Custom server configuration
custom-rendezvous-server = "$Server"
relay-server = "$RelayServer"

# Disable public servers (force connection to MSP server only)
direct-server = ""

# Lock configuration to prevent user changes
allow-auto-disconnect = true
"@
    
    # Add unattended access if password provided
    if (-not [string]::IsNullOrWhiteSpace($UnattendedPassword)) {
        Write-Log "Configuring unattended access..."
        $configContent += @"

# Unattended access enabled
allow-remote-config-modification = false
"@
        
        # Set password via command line (more secure than config file)
        $exePaths = @(
            "$env:ProgramFiles\eRemote\eRemote.exe",
            "$env:ProgramFiles\RustDesk\rustdesk.exe"
        )
        
        foreach ($exePath in $exePaths) {
            if (Test-Path $exePath) {
                try {
                    & $exePath --password $UnattendedPassword 2>&1 | Out-Null
                    Write-Log "Unattended password configured"
                    break
                }
                catch {
                    Write-Log "WARNING: Could not set unattended password via CLI"
                }
            }
        }
    }
    
    # Write configuration
    Write-Log "Writing configuration..."
    $configContent | Set-Content -Path $configPath -Force -Encoding UTF8
    
    # Get and output the eRemote ID
    $eRemoteID = Get-eRemoteID
    
    if ($eRemoteID) {
        Write-Log "eRemote ID: $eRemoteID"
        
        # Output for NinjaOne custom field capture
        Write-Host "EREMOTE_ID=$eRemoteID"
        
        # Also try to set NinjaOne custom field if ninja CLI is available
        $ninjaPath = "$env:ProgramFiles\NinjaRMMAgent\ninja.exe"
        if (Test-Path $ninjaPath) {
            try {
                & $ninjaPath --set custom:eRemoteID=$eRemoteID 2>&1 | Out-Null
                Write-Log "Updated NinjaOne custom field: eRemoteID"
            }
            catch {
                Write-Log "NOTE: Could not update NinjaOne field automatically"
            }
        }
    }
    else {
        Write-Log "WARNING: Could not determine eRemote ID. It may be assigned after first connection."
    }
    
    # Restart service to apply changes
    $serviceName = "eRemote"
    $service = Get-Service -Name $serviceName -ErrorAction SilentlyContinue
    if ($service) {
        Write-Log "Restarting eRemote service..."
        Restart-Service -Name $serviceName -Force -ErrorAction SilentlyContinue
        Start-Sleep -Seconds 3
    }
    
    Write-Log "=== eRemote Configuration Complete ==="
    Write-Log "Server: $Server"
    if ($eRemoteID) {
        Write-Log "Device ID: $eRemoteID"
    }
    
    exit 0
}
catch {
    Write-Log "ERROR: $($_.Exception.Message)"
    exit 1
}
